# Preprocessing

## notebook imports

In [2]:
! pip install nltk

Collecting nltk
  Downloading nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Collecting click (from nltk)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: joblib in /Users/iankinyanjui/.pyenv/versions/3.10.6/envs/twitpol/lib/python3.10/site-packages (from nltk) (1.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.5.15-cp310-cp310-macosx_10_9_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 741.6 kB/s eta 0:00:00 0:00:01
Collecting tqdm (from nltk)
  Downloading tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 2.6 MB/s eta 0:00:00
Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 8.4 MB/s eta 0:00:00a 0:00:01
Downloading regex-2024.5.15-cp310-cp310-macosx_10_9_x86_64.whl (281 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.7/281.7 kB 7.7 MB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 6.1 MB/s eta 0:00:00
Downloading tqdm-4.66.4-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 4.2 MB/s eta 0:00:00
Installing collected packages: tqdm, regex, click, nltk
Successfully installed click-8.1.7 nltk-3.8.1 regex-2024.5.15 tqdm-4.66.4

In [63]:
import pandas as pd
import numpy as np
import string
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

pd.set_option('display.max_columns', None)

## import raw data

In [ ]:
# csv_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__)), "raw_data")
# file_names = os.listdir(csv_path)
# paths = [os.path.join(csv_path, file_path) for file_path in file_names if file_path.endswith('.csv')]
# key_names = [key_name.replace('olist_','').replace('_dataset','').replace('.csv','') for key_name in file_names if key_name.endswith('.csv')]
# data = {}
#     for key_names, path in zip(key_names, paths): data[key_names] = pd.read_csv(path)

In [64]:
files = os.listdir('raw_data')
data = {}

for file in files:
    df = pd.read_csv(f'raw_data/{file}')
    tweets = list(df['Clean_tweet'].values) if 'Clean_tweet' in df.columns else list(df.Tweet.values)
    key = file.split('_')[0]
    data.update({key:tweets})

NameError: name 'os' is not defined

In [72]:
# JohnBoozman
pathJB = '/Users/iankinyanjui/code/kun1887/twitpol/raw_data/JohnBoozman_tweets.csv'
dfJB = pd.read_csv(pathJB)

In [73]:
# Senator Alexander
pathSA = '/Users/iankinyanjui/code/kun1887/twitpol/raw_data/SenAlexander_tweets.csv'
dfSA = pd.read_csv(pathSA)

In [74]:
# Donald Trump
pathrDT = '/Users/iankinyanjui/code/kun1887/twitpol/raw_data/realDonaldTrump_tweets.csv'
dfrDT = pd.read_csv(pathrDT)

In [77]:
dfSA

,Tweet ID,Date Created,Tweet,Clean_tweet,Polarity,Subjectivity,Retweets,Favorites,Language,User ID,User Name,User Twitter Handle,Follower Count,Friend Count,Location,Verified
0,1136740422477320192,2019-06-06,I want to wish my fellow senator from Tennesse...,want wish fellow senator from Tennessee very h...,0.500000,0.833333,19,198,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True
1,1136726200674471936,2019-06-06,One in four Americans say it is “difficult” to...,four Americans difficult afford their prescrip...,-0.250000,0.500000,4,13,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True
2,1136705409643962369,2019-06-06,"On this 75th anniversary of D-Day, I remember ...",this anniversary remember great Americans like...,0.250000,0.675000,7,60,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True
3,1136672655355142149,2019-06-06,"David Copeland was conservative, principled an...",David Copeland conservative principled diligen...,0.476700,0.033333,2,0,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True
4,1136635603808690178,2019-06-06,One reason health care is so expensive is that...,reason health care expensive that cost hidden ...,-0.141667,0.468333,2,13,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3185,852609296198225921,2017-04-13,“Next week is National Park Week. It’s a great...,Next week National Park Week great time celebr...,0.361905,0.428571,2,10,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True
3186,852592398475694084,2017-04-13,READ:Sen. Alexander writes “National Park Week...,READ Alexander writes National Park Week great...,0.542857,0.642857,6,14,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True
3187,852162157441466368,2017-04-12,Senator Alexander is working to make sure Pres...,Senator Alexander working make sure President ...,0.500000,0.888889,8,31,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True
3188,851891114978164736,2017-04-11,WATCH: Sen. Alexander was in Columbia for Mule...,WATCH Alexander Columbia Mule tour President J...,0.000000,0.000000,3,18,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True
3189,850480425185288193,2017-04-07,Alexander on selection of Tennessean Mark Gree...,Alexander selection Tennessean Mark Green Secr...,-0.200000,0.300000,5,8,en,76649729,Sen. Lamar Alexander,SenAlexander,104820,473,"Maryville, TN",True

In [57]:
example = dfrDT.iloc[120, 2]
example += ' ☹️'

In [60]:
import spacy
from spacy.tokens import Doc
import emoji
import re
import os
from pathlib import Path


files = os.listdir('raw_data')
data = {}

for file in files:
    df = pd.read_csv(f'raw_data/{file}')
    tweets = list(df['Clean_tweet'].values) if 'Clean_tweet' in df.columns else list(df.Tweet.values)
    key = file.split('_')[0]
    data.update({key:tweets})


def preprocess_text(text):
    nlp = spacy.load("en_core_web_sm")
    
    # Lowercase the text
    text = text.lower()

    # Remove sentences starting with 'RT ' or '@' (hashtags)
    if text.startswith("rt "): #or text.startswith("@"):
        return []  # Empty list for removal

    # Remove whitespace
    text = text.strip()
    
    # Remove numbers
    text = re.sub(r"[0-9]+", "", text)

    # Remove URLs
    text = re.sub(r"(http|https)?://[^\s]+", "", text)  # Match and replace URLs


    # Remove emojis using emoji library
    text = emoji.demojize(text)  # Replaces emojis with their corresponding description

    # Tokenize the text
    doc = nlp(text)
    tokens = [token for token in doc]

    # Remove stopwords
    # tokens = [token for token in tokens if not token.is_stop or not token.is_punct]
    cleanded_tokens = []
    for each in tokens:
        if each.is_punct or each.is_stop:
            continue
        else:
            cleanded_tokens.append(each)
    

    # Lemmatize the tokens
    lemmas = [token.lemma_ for token in cleanded_tokens]
    
    return lemmas

In [61]:
preprocess_text(example)

['june',
 'th',
 'united',
 'states',
 'impose',
 'tariff',
 'good',
 'come',
 'country',
 'mexico',
 'time',
 'illegal',
 'migrant',
 'come',
 'mexico',
 'country',
 'stop',
 'tariff',
 'gradually',
 'increase',
 'illegal',
 'immigration',
 'problem',
 'remedied',
 'frowning_face']